// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZLh4wMvC4SX7E5I8T9i7616xvboXu2A8',
    appId: '1:1081790602560:web:6662779044d392f0d2aea5',
    messagingSenderId: '1081790602560',
    projectId: 'eyecu-mobile-app',
    authDomain: 'eyecu-mobile-app.firebaseapp.com',
    databaseURL: 'https://eyecu-mobile-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'eyecu-mobile-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoZdhqvaLpJ1J_DwgzD2yrxJRyUzTgGts',
    appId: '1:1081790602560:android:cefa68dada1370c4d2aea5',
    messagingSenderId: '1081790602560',
    projectId: 'eyecu-mobile-app',
    databaseURL: 'https://eyecu-mobile-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'eyecu-mobile-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRR3t9gEVs3TYpN9sctSKjXD_fYnnpJtY',
    appId: '1:1081790602560:ios:5e3abb9ed0ef80f2d2aea5',
    messagingSenderId: '1081790602560',
    projectId: 'eyecu-mobile-app',
    databaseURL: 'https://eyecu-mobile-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'eyecu-mobile-app.appspot.com',
    iosClientId: '1081790602560-b8676nc9olatk5utq1cre63b03vv4k27.apps.googleusercontent.com',
    iosBundleId: 'com.example.eyecu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRR3t9gEVs3TYpN9sctSKjXD_fYnnpJtY',
    appId: '1:1081790602560:ios:5e3abb9ed0ef80f2d2aea5',
    messagingSenderId: '1081790602560',
    projectId: 'eyecu-mobile-app',
    databaseURL: 'https://eyecu-mobile-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'eyecu-mobile-app.appspot.com',
    iosClientId: '1081790602560-b8676nc9olatk5utq1cre63b03vv4k27.apps.googleusercontent.com',
    iosBundleId: 'com.example.eyecu',
  );
}
